// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArp5-uRbDeIWselfiiOZaMrP_6qkVdFGE',
    appId: '1:657097239115:web:bc0317a7dd3804c776bbce',
    messagingSenderId: '657097239115',
    projectId: 'remote-manager-95b0b',
    authDomain: 'remote-manager-95b0b.firebaseapp.com',
    storageBucket: 'remote-manager-95b0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpq2DZMJQaywH7GikOjjhyYdnVEP6xdEA',
    appId: '1:657097239115:android:ece69584fac982ae76bbce',
    messagingSenderId: '657097239115',
    projectId: 'remote-manager-95b0b',
    storageBucket: 'remote-manager-95b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1fyTUNnPpm0Awwac_IOj8rN4VuRhN1uk',
    appId: '1:657097239115:ios:d263b04981703bc776bbce',
    messagingSenderId: '657097239115',
    projectId: 'remote-manager-95b0b',
    storageBucket: 'remote-manager-95b0b.appspot.com',
    iosClientId: '657097239115-lnnbp1aidccpdhndk2l5tmuor0pabdu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1fyTUNnPpm0Awwac_IOj8rN4VuRhN1uk',
    appId: '1:657097239115:ios:d263b04981703bc776bbce',
    messagingSenderId: '657097239115',
    projectId: 'remote-manager-95b0b',
    storageBucket: 'remote-manager-95b0b.appspot.com',
    iosClientId: '657097239115-lnnbp1aidccpdhndk2l5tmuor0pabdu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteManager',
  );
}
